// <auto-generated />
using System;
using Battleship_Websockets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Battleship_Websockets.Migrations
{
    [DbContext(typeof(GameDBContext))]
    [Migration("20220418170423_gane-bf6")]
    partial class ganebf6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Battleship_Websockets.Model.BattleFieldModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BattleFields");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BattleField1Id")
                        .HasColumnType("int");

                    b.Property<int?>("BattleField2Id")
                        .HasColumnType("int");

                    b.Property<string>("ConnId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("PlayerTurn")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleField1Id");

                    b.HasIndex("BattleField2Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.PlayerGameManyToMany", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "PlayerId");

                    b.ToTable("PlayerGameManyToMany");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.PlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.Ship.ShipModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BattleFieldId")
                        .HasColumnType("int");

                    b.Property<int>("ColumnBegin")
                        .HasColumnType("int");

                    b.Property<int>("Orientation")
                        .HasColumnType("int");

                    b.Property<int>("RowBegin")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleFieldId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.Ship.ShipPart", b =>
                {
                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int?>("ShipModelId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ShipId", "Number");

                    b.HasIndex("Number");

                    b.HasIndex("ShipModelId");

                    b.ToTable("ShipParts");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.ShotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BattleFieldId")
                        .HasColumnType("int");

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoveTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BattleFieldId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Shots");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.GameModel", b =>
                {
                    b.HasOne("Battleship_Websockets.Model.BattleFieldModel", "BattleField1")
                        .WithMany()
                        .HasForeignKey("BattleField1Id");

                    b.HasOne("Battleship_Websockets.Model.BattleFieldModel", "BattleField2")
                        .WithMany()
                        .HasForeignKey("BattleField2Id");

                    b.Navigation("BattleField1");

                    b.Navigation("BattleField2");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.Ship.ShipModel", b =>
                {
                    b.HasOne("Battleship_Websockets.Model.BattleFieldModel", null)
                        .WithMany()
                        .HasForeignKey("BattleFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Battleship_Websockets.Model.Ship.ShipPart", b =>
                {
                    b.HasOne("Battleship_Websockets.Model.Ship.ShipModel", "Ship")
                        .WithMany()
                        .HasForeignKey("Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Battleship_Websockets.Model.Ship.ShipModel", null)
                        .WithMany("ShipParts")
                        .HasForeignKey("ShipModelId");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Battleship_Websockets.Model.ShotModel", b =>
                {
                    b.HasOne("Battleship_Websockets.Model.BattleFieldModel", null)
                        .WithMany()
                        .HasForeignKey("BattleFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Battleship_Websockets.Model.PlayerModel", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Battleship_Websockets.Model.Ship.ShipModel", b =>
                {
                    b.Navigation("ShipParts");
                });
#pragma warning restore 612, 618
        }
    }
}
